### ISSUE TITLE
Google Charts no longer rendering

### ISSUE THREAD

**Issue by sabi-wabi** [jcheng5/googleCharts#12]
I realised today that the demo https://shiny.rstudio.com/gallery/google-charts.html is no longer rendering the plot. Tried it in both Chrome and Edge, does not seem to be a browser related issue. I think the API is broken?

**Comment by zhenming91** [comment]
The solution is to not use

**Comment by zhenming91** [comment]
The workaround is to replace,

`googleChartsInit()` with 

`  HTML('
  <script src="https://www.gstatic.com/charts/loader.js"></script>
<script>
  google.charts.load(\'current\', {packages: [\'corechart\']});
  google.charts.setOnLoadCallback(drawChart);
</script><script src="googleCharts/bindings.js"></script>
       '),`

**Comment by isidroc** [comment]
Hello, this is not working again for me. Any other ideas? Thanks

**Comment by zhenming91** [comment]
It could because the javascript file bindings.js is not loaded properly. You could check this by going into dev tools, go to network and check the if bindings.js is loaded or not. 

What I did as a workaround was to copy the bindings.js file from the googleCharts library folder into the www folder in my app, and have my app.R to load the script directly. 

```
  HTML('
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script>
  google.charts.load(\'current\', {packages: [ "corechart"]});
  google.charts.setOnLoadCallback(drawChart);
</script>
<script src="bindings.js"></script>')
```

**Comment by isidroc** [comment]
Thanks

**Comment by alexvmt** [comment]
When I follow your advice given in the comment on June 16, the visualization works again normally at first. But when I then publish my app to shinyapps.io or restart my R session, the visualization is again not rendering. Unfortunately, your advice in your comment on July 6 also doesn't resolve my issue. Do you have any other suggestions or ideas?

**Comment by zhenming91** [comment]
I am not sure. It works locally but not when published? What's the status of loader.js and binding.js showing on the dev tools in the network tab? 

There could be various factors. Did you publish the app along with the binding.js file?

**Comment by alexvmt** [comment]
Thanks for giving feedback so quickly!

I managed to make my app run locally again following your advice and eventually figuring our where to copy bindings.js to in the shiny library directory.

I then published my app on shinyapps.io, including bindings.js, but the visualization is not rendering with a 404 status for bindings.js in the network tab. It seems as if there remains an issue with shinyapps.io because I don't really see where I could change things there.

**Comment by jcheng5** [comment]
Sorry, I had no idea people were still using this package! I've fixed it in master.

**Comment by alexvmt** [comment]
Thanks a lot for your effort! Works like a charm again.

**Comment by nstavrou** [comment]
Hello! It seems that again it is not rendering the plot correctly. 
As you can see in this example https://shiny.rstudio.com/gallery/google-charts.html when it starts playing, it changes the layout and the formatting. I have the same issue on an application of my own. 
Any ideas? 
Thanks :)

![image](https://user-images.githubusercontent.com/47423909/230477222-3a765a21-9130-46d7-84bd-f5f245db7eac.png)

![image](https://user-images.githubusercontent.com/47423909/230477307-306ed7d6-3204-4cc2-8256-c58ffd17c75e.png)
